apiVersion: 1

datasources:
  - name: Loki # Display name in Grafana
    type: loki
    access: proxy # Grafana will proxy requests to Loki
    orgId: 1
    url: http://loki:3100 # Point to the Loki service in the Docker network
    basicAuth: false # Set to true and configure if Loki has basic auth enabled
    isDefault: true # Make Loki the default datasource in Explore
    version: 1
    editable: true # Allow editing this datasource in Grafana UI
    readOnly: false